export const STANDARD_LOCATION_ZONES = [
  { code: "BOD", label: "Bodega (BOD)" },
  { code: "EMP", label: "Empaques / Estibas (EMP)" },
  { code: "REC", label: "Recepcion (REC)" },
  { code: "DSP", label: "Despacho (DSP)" },
  { code: "BODEGA", label: "Bodega principal" },
  { code: "FRIO", label: "Cuarto frio" },
  { code: "CONG", label: "Congelados" },
  { code: "N2P", label: "Nevera produccion" },
  { code: "N3P", label: "Nevera despacho" },
  { code: "SECOS1", label: "Secos" },
  { code: "SECPREP", label: "Secos preparados" },
  { code: "COC", label: "Cocina caliente" },
  { code: "BAR", label: "Bar (BAR)" },
  { code: "OFI", label: "Oficina (OFI)" },
  { code: "EXT", label: "Externo (EXT)" },
] as const;
