import { requireAppAccess } from "@/lib/auth/guard";
import { MasterProductsConfigurator } from "@/features/inventory/master-products/master-products-configurator";
export const dynamic = "force-dynamic";
export default async function MasterProductsPage() {
 const { supabase, user }=await requireAppAccess({appId:"nexo",returnTo:"/inventory/settings/products",permissionCode:"inventory.stock"});
 const [employee,products,categories,suppliers,links,policies,routes,profiles,offers,sites,siteSettings,inventoryProfiles,areas,locations,batches]=await Promise.all([supabase.from("employees").select("role").eq("id",user.id).maybeSingle(),supabase.from("products").select("id,name,sku,is_active,stock_unit_code,category_id").order("name").limit(1000),supabase.from("product_categories").select("id,name").eq("is_active",true).order("name"),supabase.from("suppliers").select("id,name").eq("is_active",true),supabase.from("product_suppliers").select("product_id,suppliers(name)").eq("is_primary",true),supabase.from("product_request_policies").select("id,product_id,label,request_unit_code,base_unit_code,base_qty_per_request_unit,minimum_request_qty,request_step_qty,is_default").eq("is_active",true).order("is_default",{ascending:false}),supabase.from("product_fulfillment_routes").select("product_id").eq("is_active",true),supabase.from("product_uom_profiles").select("id,product_id,label,input_unit_code,qty_in_stock_unit,is_active").order("label"),supabase.from("product_suppliers").select("product_id,uom_profile_id,purchase_unit,purchase_pack_qty,purchase_pack_unit_code,purchase_price,currency,is_primary,suppliers(name)"),supabase.from("sites").select("id,name").eq("is_active",true).order("name"),supabase.from("product_site_settings").select("product_id,site_id,is_active,inventory_enabled,remission_enabled,sales_enabled,min_stock_qty"),supabase.from("product_inventory_profiles").select("product_id,track_inventory,inventory_kind,lot_tracking,expiry_tracking,measurement_mode,default_tolerance_percent"),supabase.from("area_kinds").select("code,name").order("name"),supabase.from("inventory_locations").select("id,site_id,name").eq("is_active",true).order("name"),supabase.from("product_configuration_batches").select("id,zone,product_count,created_at").order("created_at",{ascending:false}).limit(12)]);
 const categoryMap=new Map((categories.data??[]).map((x:any)=>[x.id,x.name])); const supplierMap=new Map((links.data??[]).map((x:any)=>[x.product_id,Array.isArray(x.suppliers)?x.suppliers[0]?.name:x.suppliers?.name])); const policyIds=new Set((policies.data??[]).map((x:any)=>x.product_id)); const routeIds=new Set((routes.data??[]).map((x:any)=>x.product_id));
 const policyByProduct=new Map((policies.data??[]).map((x:any)=>[x.product_id,x])); const rows=(products.data??[]).map((x:any)=>({id:x.id,name:x.name??"Sin nombre",sku:x.sku,isActive:Boolean(x.is_active),categoryId:x.category_id,category:categoryMap.get(x.category_id)??null,supplier:supplierMap.get(x.id)??null,stockUnit:x.stock_unit_code,hasPolicy:policyIds.has(x.id),hasRoute:routeIds.has(x.id),requestPolicy:policyByProduct.get(x.id)??null}));
 const productName=new Map(rows.map(x=>[x.id,x.name])); const profileOffer=new Map((offers.data??[]).filter((x:any)=>x.uom_profile_id).map((x:any)=>[x.uom_profile_id,x]));
 const presentations=(profiles.data??[]).map((x:any)=>{const offer:any=profileOffer.get(x.id);return {id:x.id,productId:x.product_id,productName:productName.get(x.product_id)??"Producto no disponible",label:x.label,inputUnit:x.input_unit_code,stockQty:x.qty_in_stock_unit,stockUnit:rows.find(row=>row.id===x.product_id)?.stockUnit??null,isActive:Boolean(x.is_active),supplierLinkId:offer?.id??null,supplier:offer?(Array.isArray(offer.suppliers)?offer.suppliers[0]?.name:offer.suppliers?.name)??null:null,purchaseUnit:offer?.purchase_pack_unit_code??offer?.purchase_unit??null,purchasePackQty:offer?.purchase_pack_qty??null,purchasePrice:offer?.purchase_price??null,currency:offer?.currency??"COP",isPrimary:Boolean(offer?.is_primary)}});
 const siteSettingsRows=(siteSettings.data??[]).map((x:any)=>({productId:x.product_id,siteId:x.site_id,isActive:Boolean(x.is_active),inventoryEnabled:x.inventory_enabled!==false,remissionEnabled:Boolean(x.remission_enabled),salesEnabled:Boolean(x.sales_enabled),minStockQty:Number(x.min_stock_qty??0)}));
 const inventoryProfileRows=(inventoryProfiles.data??[]).map((x:any)=>({productId:x.product_id,trackInventory:x.track_inventory!==false,inventoryKind:x.inventory_kind??"unclassified",lotTracking:Boolean(x.lot_tracking),expiryTracking:Boolean(x.expiry_tracking),measurementMode:x.measurement_mode??"fixed_presentation",defaultTolerancePercent:Number(x.default_tolerance_percent??0)}));
 const canApply=["propietario","gerente_general"].includes(String((employee.data as any)?.role??"").toLowerCase());
 return <MasterProductsConfigurator canApply={canApply} rows={rows} categories={(categories.data??[]).map((x:any)=>({id:x.id,name:x.name}))} suppliers={Array.from(new Set(rows.map(x=>x.supplier).filter(Boolean))) as string[]} presentations={presentations} sites={(sites.data??[]).map((x:any)=>({id:x.id,name:x.name}))} siteSettings={siteSettingsRows} inventoryProfiles={inventoryProfileRows} areas={(areas.data??[]).map((x:any)=>({code:x.code,name:x.name}))} locations={(locations.data??[]).map((x:any)=>({id:x.id,siteId:x.site_id,name:x.name}))} batches={(batches.data??[]).map((x:any)=>({id:x.id,zone:x.zone,productCount:x.product_count,createdAt:x.created_at}))}/>;
}
