import { requireAppAccess } from "@/lib/auth/guard";
import { RequestPolicyManager,type ManagerProduct } from "./request-policy-manager";

export const dynamic="force-dynamic";const APP_ID="nexo",PERMISSION="inventory.stock";
type ProductRow={id:string;name:string|null;sku:string|null;product_type:string|null;stock_unit_code:string|null;unit:string|null;category?:{name?:string|null}|{name?:string|null}[]|null};
type ProfileRow={product_id:string;inventory_kind:string|null;measurement_mode:string|null;default_tolerance_percent:number|null;aux_count_unit_code:string|null;requires_actual_production_qty:boolean|null;requires_actual_dispatch_qty:boolean|null;requires_actual_receipt_qty:boolean|null;requires_count_alongside_weight:boolean|null};
type PolicyRow={id:string;product_id:string;label:string;request_unit_code:string;base_unit_code:string;base_qty_per_request_unit:number;minimum_request_qty:number|null;request_step_qty:number|null;allow_fraction:boolean};
type PresentationRow={id:string;product_id:string;label:string;input_unit_code:string;qty_in_stock_unit:number;image_url:string|null;catalog_image_url:string|null};
type LinkRow={request_policy_id:string;uom_profile_id:string;is_preferred:boolean};
type OfferRow={id:string;product_id:string;supplier_sku:string|null;supplier_product_alias:string|null;purchase_unit:string|null;is_primary:boolean|null;uom_profile_id:string|null;suppliers?:{name?:string|null}|{name?:string|null}[]|null};
function relatedName(v:ProductRow["category"]|OfferRow["suppliers"]){const r=Array.isArray(v)?v[0]:v;return String(r?.name??"").trim()}
function effectiveType(type:string|null,kind:string|null){if(String(kind??"").toLowerCase()==="asset")return"Activo";const t=String(type??"").toLowerCase();if(t==="preparacion")return"Preparación";if(t==="venta")return"Venta";return"Insumo"}
function mode(value:string|null):"fixed_presentation"|"variable_weight"|"count_with_weight"|"bulk_volume"{const v=String(value??"");return v==="variable_weight"||v==="count_with_weight"||v==="bulk_volume"?v:"fixed_presentation"}

export default async function RequestPoliciesPage(){
 const{supabase}=await requireAppAccess({appId:APP_ID,returnTo:"/inventory/settings/request-policies",permissionCode:PERMISSION});
 const[{data:productsData,error:productsError},{data:profilesData,error:profilesError},{data:policiesData,error:policiesError},{data:presentationsData,error:presentationsError},{data:linksData,error:linksError},{data:offersData,error:offersError}]=await Promise.all([
  supabase.from("products").select("id,name,sku,product_type,stock_unit_code,unit,category:product_categories(name)").eq("is_active",true).order("name"),
  supabase.from("product_inventory_profiles").select("product_id,inventory_kind,measurement_mode,default_tolerance_percent,aux_count_unit_code,requires_actual_production_qty,requires_actual_dispatch_qty,requires_actual_receipt_qty,requires_count_alongside_weight"),
  supabase.from("product_request_policies").select("id,product_id,label,request_unit_code,base_unit_code,base_qty_per_request_unit,minimum_request_qty,request_step_qty,allow_fraction").eq("is_active",true).eq("is_default",true),
  supabase.from("product_uom_profiles").select("id,product_id,label,input_unit_code,qty_in_stock_unit,image_url,catalog_image_url").eq("is_active",true).order("label"),
  supabase.from("product_request_policy_presentations").select("request_policy_id,uom_profile_id,is_preferred"),
  supabase.from("product_suppliers").select("id,product_id,supplier_sku,supplier_product_alias,purchase_unit,is_primary,uom_profile_id,suppliers(name)").order("is_primary",{ascending:false}),
 ]);
 const err=productsError||profilesError||policiesError||presentationsError||linksError||offersError;if(err)throw new Error(err.message);
 const products=(productsData??[])as ProductRow[],profiles=(profilesData??[])as ProfileRow[],policies=(policiesData??[])as PolicyRow[],presentations=(presentationsData??[])as PresentationRow[],links=(linksData??[])as LinkRow[],offers=(offersData??[])as OfferRow[];
 const profileByProduct=new Map(profiles.map(r=>[r.product_id,r])),policyByProduct=new Map(policies.map(r=>[r.product_id,r]));
 const presentationsByProduct=new Map<string,PresentationRow[]>(),linksByPolicy=new Map<string,LinkRow[]>(),offersByProduct=new Map<string,OfferRow[]>();
 for(const r of presentations)presentationsByProduct.set(r.product_id,[...(presentationsByProduct.get(r.product_id)??[]),r]);for(const r of links)linksByPolicy.set(r.request_policy_id,[...(linksByPolicy.get(r.request_policy_id)??[]),r]);for(const r of offers)offersByProduct.set(r.product_id,[...(offersByProduct.get(r.product_id)??[]),r]);
 const rows:ManagerProduct[]=products.map(product=>{const profile=profileByProduct.get(product.id)??null,policy=policyByProduct.get(product.id)??null,productPresentations=presentationsByProduct.get(product.id)??[],policyLinks=policy?linksByPolicy.get(policy.id)??[]:[];const fallback=policy?productPresentations.find(p=>Number(p.qty_in_stock_unit)===Number(policy.base_qty_per_request_unit))?.id??null:null;const presentationIds=policyLinks.length?policyLinks.map(l=>l.uom_profile_id):fallback?[fallback]:[];return{id:product.id,name:String(product.name??"Producto").trim(),sku:String(product.sku??"").trim(),categoryName:relatedName(product.category),productType:effectiveType(product.product_type,profile?.inventory_kind??null),baseUnitCode:String(product.stock_unit_code||product.unit||policy?.base_unit_code||"un").trim(),policy:{id:policy?.id??null,label:String(policy?.label??"").trim(),requestUnitCode:String(policy?.request_unit_code??"").trim(),baseQtyPerRequestUnit:Number(policy?.base_qty_per_request_unit??1),minimumRequestQty:Number(policy?.minimum_request_qty??1),requestStepQty:Number(policy?.request_step_qty??1),allowFraction:Boolean(policy?.allow_fraction),presentationIds,preferredPresentationId:policyLinks.find(l=>l.is_preferred)?.uom_profile_id??presentationIds[0]??null},measurement:{measurementMode:mode(profile?.measurement_mode??null),tolerancePercent:Number(profile?.default_tolerance_percent??0),auxCountUnitCode:String(profile?.aux_count_unit_code??""),requiresActualProductionQty:Boolean(profile?.requires_actual_production_qty),requiresActualDispatchQty:Boolean(profile?.requires_actual_dispatch_qty),requiresActualReceiptQty:Boolean(profile?.requires_actual_receipt_qty),requiresCountAlongsideWeight:Boolean(profile?.requires_count_alongside_weight)},presentations:productPresentations.map(p=>({id:p.id,label:p.label,inputUnitCode:p.input_unit_code,qtyInStockUnit:Number(p.qty_in_stock_unit),imageUrl:String(p.image_url||p.catalog_image_url||"")})),supplierOffers:(offersByProduct.get(product.id)??[]).map(o=>({id:o.id,supplierName:relatedName(o.suppliers)||"Proveedor",supplierAlias:String(o.supplier_product_alias??"").trim(),supplierSku:String(o.supplier_sku??"").trim(),purchaseUnit:String(o.purchase_unit??"").trim(),isPrimary:Boolean(o.is_primary),uomProfileId:o.uom_profile_id}))}});
 return <div className="ui-scene w-full space-y-6"><section className="ui-panel ui-panel--halo"><div className="ui-caption">Catálogo · configuración masiva</div><h1 className="mt-2 ui-h1">Unidades, medición, presentaciones y proveedores</h1><p className="mt-2 max-w-4xl ui-body-muted">Configura cómo se solicita, cómo se mide realmente y qué presentaciones físicas cumplen cada producto.</p></section><RequestPolicyManager products={rows}/></div>;
}
